"""wordlists table renamed to vocabrecords

Revision ID: 3e33e1dee3bd
Revises: 4132dfb9a7d4
Create Date: 2019-06-01 16:04:44.448469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e33e1dee3bd'
down_revision = '4132dfb9a7d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vocab_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=140), nullable=True),
    sa.Column('translation', sa.String(length=140), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('wordlist')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wordlist',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('word', sa.VARCHAR(length=140), nullable=True),
    sa.Column('translation', sa.VARCHAR(length=140), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('vocab_record')
    # ### end Alembic commands ###
