"""wordlists table

Revision ID: 4132dfb9a7d4
Revises: 6df46bce3d5d
Create Date: 2019-06-01 15:34:23.489803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4132dfb9a7d4'
down_revision = '6df46bce3d5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wordlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=140), nullable=True),
    sa.Column('translation', sa.String(length=140), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wordlist')
    # ### end Alembic commands ###
